### ISSUE TITLE
NRK Nett-TV addon problem

### ISSUE THREAD

**Issue by jonnyns** [tamland/xbmc-addon-nrk#85]
Very recently 
NRK Nett-TV addon version 4.11.0 stopped working on LibreELEC 12.2.1 (Kodi 21 / Python 3.11).

Error in kodi.log:

ImportError: cannot import name 'override' from typing (/usr/lib/python3.11/typing.py)

The addon imports:

from typing import Any, override

but typing.override was introduced in Python 3.12, while LibreELEC 12.x still uses Python 3.11.

A temporary workaround was to modify the addon code to provide a fallback:

try:
from typing import override
except ImportError:
def override(func):
return func

After this change the addon works again.

It seems the current addon version assumes Python 3.12 and therefore breaks on LibreELEC 12.x.

System:
LibreELEC 12.2.1
Kodi 21 (Omega)
NRK Nett-TV addon 4.11.0

Hope this helps identify the issue.
